### ISSUE TITLE
pyaudio

### ISSUE THREAD

**Issue by kimakuma** [TomPrograms/Python-Voice-Chat#3]
I can't download  the pyaudio package.
It printed "Unable to locate package pyaudio"
I founded various solutions, but It doesn't work.

Also, the sound wasn't send between server and client, however I checked connection worked well.

I don't know why happened this problems so, I want your help.
I wait you everyday.

**Comment by kimakuma** [comment]
PLS give me the answer.
I don't want a perfect solution, but I need your confirmation.

**Comment by TomPrograms** [comment]
Hi. I'm not sure why this is happening for you, and I don't think it's a problem with the code, rather than some problem with your system. 

Try this answer: https://stackoverflow.com/questions/52283840/i-cant-install-pyaudio-on-windows-how-to-solve-error-microsoft-visual-c-14. Other than that, I'm not sure. Sorry.
