### ISSUE TITLE
Latency 

### ISSUE THREAD

**Issue by EliotAmn** [TomPrograms/Python-Voice-Chat#5]
Hi, sorry for my bad english.
This work fine, but as things progress, the audio add a little latency. 
1 hour later, 2min of latency lol
(Server and client hosted in same computer)

**Comment by ChetanyaPathak** [comment]
Hey if you dont mind can you explain how got the port forwarding to work?

**Comment by yuqizhi** [comment]
why not use UDP??

**Comment by TomPrograms** [comment]
I've had this issue before, and I wasn't sure what specifically was causing it. Would moving to UDP, rather than TCP really reduce that latency though?

**Comment by TomPrograms** [comment]
@ChetanyaPathak port forwarding is system specific I'm pretty sure. Try looking up a guide for whatever platform (Windows/Linux etc.) you're on, and ensuring your router is forwarding traffic for the port you want to use for the application onto your computer. This is only necessary if you're running the server/client across a network rather than both locally.

**Comment by yuqizhi** [comment]
@TomPrograms @EliotAmn I'm not sure, but we can try

**Comment by Eyles1** [comment]
@ChetanyaPathak 
You can use ngrok
